extends Node
## Stage curtain (close / open / reveal, covering: mute, focus view, room light) and the
## control panel in its own window.
func _secs(t): await get_tree().create_timer(t).timeout
func _shot(path):
	await RenderingServer.frame_post_draw
	get_viewport().get_texture().get_image().save_png(path)
func _ready():
	var out: String = OS.get_cmdline_user_args()[0]
	AppState.set_setting("chat_enabled", false)
	AppState.set_setting("curtain_enabled", true)
	AppState.set_setting("curtain_sign", "")
	AppState.set_setting("panel_window", false)
	var main = load("res://core/main.tscn").instantiate()
	add_child(main)
	await _secs(0.5)
	AppState.request_room("lecture_hall_panel")
	await _secs(4.0)
	var room = main.get_node("RoomHost").get_current_room()
	var curtain: StageCurtain = room.find_child("StageCurtain", true, false)
	print("curtain=", curtain != null, " open=", curtain.get_open_amount())
	var bus := AudioServer.get_bus_index("Video")
	# close, with a sign
	AppState.set_setting("curtain_sign", "Be right back")
	AppState.set_curtain(true)
	await _secs(0.8)
	await _shot(out + "/curtain_closing.png")
	await _secs(2.0)
	print("closed open=", snappedf(curtain.get_open_amount(), 0.01), " covering=", AppState.is_curtain_covering(), " video db=", snappedf(AudioServer.get_bus_volume_db(bus), 0.1))
	await _shot(out + "/curtain_closed.png")
	AppState.toggle_focus_view()
	await _secs(0.6)
	await _shot(out + "/curtain_focus.png")
	AppState.toggle_focus_view()
	await _secs(0.5)
	EventBus.camera_preset_requested.emit(1)
	await _secs(1.5)
	await _shot(out + "/curtain_closed_cam2.png")
	EventBus.camera_preset_requested.emit(0)
	await _secs(1.0)
	# reveal
	AppState.reveal_curtain()
	await _secs(1.0)
	print("reveal roll: dimmed=", AppState.is_show_dimmed(), " covering=", AppState.is_curtain_covering(), " open=", snappedf(curtain.get_open_amount(), 0.01))
	await _shot(out + "/curtain_roll.png")
	await _secs(2.6)
	print("reveal opening: covering=", AppState.is_curtain_covering(), " video db=", snappedf(AudioServer.get_bus_volume_db(bus), 0.1), " open=", snappedf(curtain.get_open_amount(), 0.01))
	await _shot(out + "/curtain_opening.png")
	await _secs(4.0)
	print("after reveal: dimmed=", AppState.is_show_dimmed(), " open=", snappedf(curtain.get_open_amount(), 0.01))
	await _shot(out + "/curtain_open.png")
	# theater: the curtain follows into another room, closed
	AppState.set_curtain(true, "instant")
	AppState.request_room("theater")
	await _secs(4.0)
	var room2 = main.get_node("RoomHost").get_current_room()
	var c2: StageCurtain = room2.find_child("StageCurtain", true, false)
	print("theater curtain=", c2 != null, " open=", c2.get_open_amount() if c2 else -1.0, " covering=", AppState.is_curtain_covering())
	await _shot(out + "/curtain_theater.png")
	# control panel in its own window
	var panel = main.get_node("ControlPanel")
	panel.toggle_window()
	await _secs(1.0)
	print("panel window=", panel.is_in_window(), " windows=", DisplayServer.get_window_list().size())
	await _shot(out + "/panel_popped.png")
	panel.toggle_window()
	await _secs(0.5)
	print("panel docked=", not panel.is_in_window())
	print("DONE")
	AppState.request_quit()
